In [113]:
import pandas as pd

df = pd.read_csv("/content/cleaned_it_services_tickets.csv")

 # Extract numeric matrix from cleaned pandas dataframe
numeric_cols = ['hours_logged', 'billing_rate_(usd)', 'billable_amount_usd', 'resolution_time_hours', 'csat_score']
mat = df[numeric_cols].dropna(how='all').to_numpy()

/tmp/ipykernel_623/1865260231.py:3: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("/content/cleaned_it_services_tickets.csv")


**1. Import NumPy and print its version.**

In [114]:
import numpy as np

print("Numpy version: ", np.__version__)

Numpy version:  2.1.3


Import and prints installed NumPy library version.

**2. Make an array from the hours logged column.**

In [115]:
hours = mat[:, 0]

hours

array([nan, 1.34, 7.0, ..., 47.0, 2.0, nan], dtype=object)

Extracts hours_logged values as a 1D NumPy array.

**3. Print the shape, the size and the data type of that array.**

In [116]:
print("Shape:", hours.shape, "| Size:", hours.size, "| Dtype:", hours.dtype)

Shape: (48123,) | Size: 48123 | Dtype: object


Displays dimensional structure, total element count, and data type of hours array.

**4. Make an array of the numbers 1 to 50 using arange.**

In [117]:
arr1 = np.arange(1, 51)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

Generates array of sequential integers from 1 up to 50.

**5. Make 10 evenly spaced numbers between 0 and 100 using linspace.**

In [118]:
arr2 = np.linspace(0, 100, 10) # Dividing 100 into 10 equal parts
arr2

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

Creates 10 uniformly spaced continuous float values across the range 0 to 100.

**6. Make an array of 10 zeros and an array of 10 ones.**

In [119]:
arr_zeros = np.zeros(10)
arr_ones = np.ones(10)

print("Array of Zeros: ", arr_zeros)
print("Array od Ones: ", arr_ones)

Array of Zeros:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Array od Ones:  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


Initializes arrays with 10 elements filled entirely with 0.0 and 1.0 floating values.

**7. Make a 3 by 3 array of random numbers using seed 42.**

In [120]:
np.random.seed(42)
arr_3x3 = np.random.rand(3, 3)

print(arr_3x3)

[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]


Generates reproducible 3x3 uniform random array  where values are bounded in 0 and 1.

**8. Make a 2-D array from the hours logged and billing rate columns.**

In [121]:
hours_rate = mat[:, :2]

print(hours_rate)

[[nan 39.45]
 [1.34 33.15]
 [7.0 48.1]
 ...
 [47.0 nan]
 [2.0 116.76]
 [nan 89.02]]


Combines two numerical columns into a 2D matrix.  

**9. Print how many dimensions that 2-D array has.**

In [122]:
print("Dimensions of hours_rate array:", hours_rate.ndim)

Dimensions of hours_rate array: 2


Gets array dimensions.

**10. Print the first 5 values of the hours array.**

In [123]:
print(hours[:5])

[nan 1.34 7.0 34.63 12.76]


Prints first five elements from array.

**11. Print the last 5 values of the hours array.**

In [124]:
print(hours[-5:])

[50.0 4.0 47.0 2.0 nan]


Prints last five elements from array.

**12. Print every second value from the first 20 values.**

In [125]:
print(hours[:20:2])

[nan 7.0 12.76 nan 1.66 nan 11.63 28.0 0.59 253.85]


Extracts values from index 0 to 19 stepping by 2 from array.

**13. Reverse the array.**

In [126]:
print(hours[::-1])

[nan 2.0 47.0 ... 7.0 1.34 nan]


Reverses the element order of the array using step slicing.

**14. Find the sum of the hours array.**

In [127]:
print("Sum:", np.nansum(hours))

Sum: 2290016.5500000212


Calculates total cumulative hours logged from array.

**15. Find the mean, the minimum and the maximum of the hours array.**

In [128]:
print("Mean:", np.nanmean(hours))
print("Min:", np.nanmin(hours))
print("Max:", np.nanmax(hours))

Mean: 63.16764267784794
Min: -12.5
Max: 9888.01


Computes average, minimum and maximum hours in array.

**16. Find the standard deviation.**

In [129]:
print("Standard Deviation:", np.nanstd(hours))

Standard Deviation: 493.3142529221533


Measures data dispersion and variance spread around the mean logged hours.

**17. Find the median.**

In [130]:
print("Median:", np.nanmedian(hours))

Median: 13.1


Identifies the midpoint value in the hours array.  

**18. Count how many values are missing in the array.**

In [131]:
hours = pd.to_numeric(hours, errors='coerce').astype(float)
print("Missing values count:", np.isnan(hours).sum())

Missing values count: 11870


Counts total missing (NaN) entries in the hours array.

**19. Find the mean while ignoring the missing values.**

In [132]:
print("NaN-free Mean:", np.nanmean(hours))

NaN-free Mean: 63.16764267784735


Computes average of values excluding missing entries.

**20. Replace all the missing values with 0.**

In [133]:
hours = np.nan_to_num(hours, nan=0.0)

Replacing missing NaN elements in the NumPy array with 0.0.

**21. Count how many values are greater than 100.**

In [134]:
print(np.sum(hours > 100))

1588


Counts the total number of entries in the hours array that are greater than 100 hours.

**22. Show only the values that are greater than 100.**

In [135]:
print(hours[hours > 100])

[ 253.85  128.   1900.66 ...  562.22  141.9   137.56]


Filter all array elements greater than 100.

**23. Show the values that are between 10 and 50.**

In [136]:
print(hours[(hours >= 10) & (hours <= 50)])

[34.63 12.76 15.3  ... 25.23 50.   47.  ]


Filters array elements in the range of 10 to 50.

**24. Count how many values are negative.**

In [137]:
print(np.sum(hours < 0))

136


Identifies data anomalies by counting how many hour entries are negative numbers.

**25. Replace all the negative values with 0.**

In [138]:
hours = np.where(hours < 0, 0, hours)

print(hours)

[ 0.    1.34  7.   ... 47.    2.    0.  ]


Relacing invalid negative values in the array with 0, as hours cannot be negative.

**26. Sort the array from smallest to largest.**

In [139]:
hours_sorted = np.sort(hours)

print(hours_sorted)

[   0.      0.      0.   ... 8760.   9888.01 9888.01]


Sorted the hours array in ascending order (default).

**27. Find the position of the largest value.**

In [140]:
print(np.nanargmax(hours))

10041


Returns the index of maximum value of hours in the array.

**28. Find the position of the smallest value.**

In [141]:
print(np.nanargmin(hours))

0


Returns the index of minimum value of hours in the array.

**29. Find the 5 largest values.**

In [142]:
print(np.sort(hours[~np.isnan(hours)])[-5:])

[8760.   8760.   8760.   9888.01 9888.01]


Filters 5 highest hours values in array.

**30. Round every value to 1 decimal place.**

In [143]:
print(np.round(hours, 1))

[ 0.   1.3  7.  ... 47.   2.   0. ]


Rounds all values in the array to 1 decimal place.

**31. Multiply every value by 2.**

In [144]:
print(hours * 2)

[ 0.    2.68 14.   ... 94.    4.    0.  ]


Performs element-wise multiplication to double every value in the array.

**32. Add 10 to every value.**

In [145]:
print(hours + 10)

[10.   11.34 17.   ... 57.   12.   10.  ]


Increments every element in the array by 10.

**33. Multiply the hours array by the billing rate array.**

In [146]:
billing_rate = mat[:, 1]

calculated_total = hours * billing_rate
print(calculated_total)

[0.0 44.421 336.7 ... nan 233.52 0.0]


Performs element-wise multiplication between two 1D arrays to calculate total billable amount.

**34. Check whether the two arrays have the same length.**

In [147]:
print(len(hours) == len(billing_rate))

True


Evaluates if both arrays contain an equal number of elements.

**35. Use np.where to mark values above 24 as slow and the rest as fast.**

In [148]:
speed_labels = np.where(hours > 24, 'slow', 'fast')

print(speed_labels)

['fast' 'fast' 'fast' ... 'slow' 'fast' 'fast']


Categorizes hours logged on same ticket based on a 24-hour threshold.

**36. Make an array of the unique priority values.**

In [149]:
unique_priorities = np.unique(df['priority'].dropna())

print(unique_priorities)

[' ' '--' '1' '2' '3' '4' '?' 'CRITICAL' 'Critical' 'HIGH' 'High' 'LOW'
 'Low' 'MEDIUM' 'Medium' 'P1' 'P1 - Critical' 'P2' 'P3' 'P4' 'PRIORITY'
 'high' 'low' 'medium' 'missing' 'na' 'p1' 'p2' 'p3' 'p4']


Returns a NumPy array containing all distinct priority categories in the dataset.

**37. Count how many times each unique priority value appears.**

In [150]:
priorities, counts = np.unique(df['priority'].dropna(), return_counts=True)
dict(zip(priorities, counts))

{' ': np.int64(95),
 '--': np.int64(107),
 '1': np.int64(1931),
 '2': np.int64(1966),
 '3': np.int64(1934),
 '4': np.int64(1919),
 '?': np.int64(85),
 'CRITICAL': np.int64(1993),
 'Critical': np.int64(2000),
 'HIGH': np.int64(1950),
 'High': np.int64(2003),
 'LOW': np.int64(1945),
 'Low': np.int64(1840),
 'MEDIUM': np.int64(1949),
 'Medium': np.int64(1941),
 'P1': np.int64(1891),
 'P1 - Critical': np.int64(1969),
 'P2': np.int64(1907),
 'P3': np.int64(1950),
 'P4': np.int64(1880),
 'PRIORITY': np.int64(1),
 'high': np.int64(1971),
 'low': np.int64(1950),
 'medium': np.int64(2023),
 'missing': np.int64(125),
 'na': np.int64(130),
 'p1': np.int64(1934),
 'p2': np.int64(1898),
 'p3': np.int64(1988),
 'p4': np.int64(1909)}

Calculates the exact occurrence counts for each unique priority category.  

**38. Take the first 100 values and reshape them into a 10 by 10 array.**

In [161]:
#arr_10x10 = hours[:100].reshape(10, 10)
arr_10x10 = np.arange(1, 101).reshape(10, 10)

print(arr_10x10)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


Gets first  100 values and restructures them into a 10x10 2D matrix.  

**39. Transpose that 10 by 10 array.**

In [162]:
print(arr_10x10.T)

[[  1  11  21  31  41  51  61  71  81  91]
 [  2  12  22  32  42  52  62  72  82  92]
 [  3  13  23  33  43  53  63  73  83  93]
 [  4  14  24  34  44  54  64  74  84  94]
 [  5  15  25  35  45  55  65  75  85  95]
 [  6  16  26  36  46  56  66  76  86  96]
 [  7  17  27  37  47  57  67  77  87  97]
 [  8  18  28  38  48  58  68  78  88  98]
 [  9  19  29  39  49  59  69  79  89  99]
 [ 10  20  30  40  50  60  70  80  90 100]]


Flips the 10x10 matrix over its diagonal, swapping rows and columns.

**40. Flatten it back into a 1-D array.**

In [163]:
print(arr_10x10.T.flatten())

[  1  11  21  31  41  51  61  71  81  91   2  12  22  32  42  52  62  72
  82  92   3  13  23  33  43  53  63  73  83  93   4  14  24  34  44  54
  64  74  84  94   5  15  25  35  45  55  65  75  85  95   6  16  26  36
  46  56  66  76  86  96   7  17  27  37  47  57  67  77  87  97   8  18
  28  38  48  58  68  78  88  98   9  19  29  39  49  59  69  79  89  99
  10  20  30  40  50  60  70  80  90 100]


Transforms transposed 2D matrix back into a single 1D array.

**41. Join two arrays together using np.concatenate.**

In [159]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
concatenated_arr = np.concatenate((arr1, arr2))

print(concatenated_arr)

[1 2 3 4 5 6]


.concatenate() function used to merge two 1D arrays in single array.

**42. Split an array into 5 equal parts.**

In [165]:
split_parts = np.split(arr_10x10, 5)

print(split_parts)

[array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]]), array([[21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40]]), array([[41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60]]), array([[61, 62, 63, 64, 65, 66, 67, 68, 69, 70],
       [71, 72, 73, 74, 75, 76, 77, 78, 79, 80]]), array([[ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])]


Spliting the numbers array into 5 arrays having equal elements.

**43. Find the 25th, 50th and 75th percentile.**

In [166]:
data_points = np.array([12, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60])
p25, p50, p75 = np.percentile(data_points, [25, 50, 75])

print("25th:", p25, "50th:", p50, "75th:", p75)

25th: 22.5 50th: 35.0 75th: 47.5


Calculates percentiles of element values from array.

**44. Find the cumulative sum of the first 20 values.**

In [167]:
first_20 = np.arange(1, 21)
cumulative_sum = np.cumsum(first_20)

print(cumulative_sum)

[  1   3   6  10  15  21  28  36  45  55  66  78  91 105 120 136 153 171
 190 210]


Calculates cumulative sum as incremental sum of numbers in array.

**45. Find the difference between each value and the one before it using np.diff.**

In [170]:
series = np.array([10, 15, 18, 25, 30])

differences = np.diff(series)

print(differences)

[5 3 7 5]


Calculates the difference between consecutive numbers in array.

**46. Keep every value inside the range 0 to 100 using np.clip.**

In [173]:
raw_values = np.array([-15, 5, 50, 95, 120, 200])

clipped_values = np.clip(raw_values, 0, 100)

print(clipped_values)

[  0   5  50  95 100 100]


Adjusts the elements in array in range of 0 to 100 such that below values replaced with lower bound and greater values with upper bound.

**47. Convert the array to whole numbers.**

In [174]:
float_array = np.array([1.2, 3.8, 5.5, 7.1])
integer_array = float_array.astype(int)

print(integer_array)

[1 3 5 7]


Converts decimal numbers in whole numbers.

**48. Copy the array, change one value in the copy, and show that the original did not change.**

In [175]:
original = np.array([10, 20, 30, 40])
copy_arr = original.copy()
copy_arr[0] = 999

print("Original:", original)
print("Copy:", copy_arr)

Original: [10 20 30 40]
Copy: [999  20  30  40]


When object is copied to another object, making changes on one did not affect the other.

**49. Save the array to a .npy file and load it back.**

In [178]:
np.save('/content/saved_data.npy', original)

loaded_array = np.load('saved_data.npy')

print(loaded_array)

[10 20 30 40]


SAved the array data in numpy file and read same using .load() method.

**50. Find the total revenue using np.dot on the hours array and the rate array.**

In [188]:
valid_entries = ~np.isnan(hours) & ~np.isnan(billing_rate)

hours_valid = hours[valid_entries]
rate_valid = billing_rate[valid_entries]

#total_revenue = np.dot(hours, billing_rate)
total_revenue = np.dot(hours_valid, rate_valid)

print(total_revenue)

127427757.53480002


Calculated the total revenue as product of billing rate and number of hours logged for billing.